spring.application.name=cycle-shop-backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:cycleshopdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.com.cycleshop=INFO
